// Code generated for darwin/arm64 by 'ccgo -c -ignore-unsupported-alignment -DHAVE_CONFIG_H -D__attribute__(x)= -Ithird_party/e2fsprogs/lib -Ithird_party/e2fsprogs/lib/ext2fs -Ithird_party/e2fsprogs/lib/blkid -Ithird_party/e2fsprogs/lib/e2p -Ithird_party/e2fsprogs/lib/et -Ithird_party/e2fsprogs/lib/support -Ithird_party/e2fsprogs/lib/uuid -Ithird_party/e2fsprogs/include -Ithird_party/e2fsprogs/misc -Ithird_party/e2fsprogs -o internal/e2fs/lib/et/et_name.o.go third_party/e2fsprogs/lib/et/et_name.c', DO NOT EDIT.

//go:build ignore
// +build ignore

package __ccgo_object_file_v1

const mvBITS_PER_CHAR = 6
const mvCONFIG_BUILD_FINDFS = 1
const mvCONFIG_MMP = 1
const mvCONFIG_TDB = 1
const mvCONFIG_TESTIO_DEBUG = 1
const mvE2BIG = 7
const mvEACCES = 13
const mvEADDRINUSE = 48
const mvEADDRNOTAVAIL = 49
const mvEAFNOSUPPORT = 47
const mvEAGAIN = 35
const mvEALREADY = 37
const mvEAUTH = 80
const mvEBADARCH = 86
const mvEBADEXEC = 85
const mvEBADF = 9
const mvEBADMACHO = 88
const mvEBADMSG = 94
const mvEBADRPC = 72
const mvEBUSY = 16
const mvECANCELED = 89
const mvECHILD = 10
const mvECONNABORTED = 53
const mvECONNREFUSED = 61
const mvECONNRESET = 54
const mvEDEADLK = 11
const mvEDESTADDRREQ = 39
const mvEDEVERR = 83
const mvEDOM = 33
const mvEDQUOT = 69
const mvEEXIST = 17
const mvEFAULT = 14
const mvEFBIG = 27
const mvEFTYPE = 79
const mvEHOSTDOWN = 64
const mvEHOSTUNREACH = 65
const mvEIDRM = 90
const mvEILSEQ = 92
const mvEINPROGRESS = 36
const mvEINTR = 4
const mvEINVAL = 22
const mvEIO = 5
const mvEISCONN = 56
const mvEISDIR = 21
const mvELAST = 107
const mvELOOP = 62
const mvEMFILE = 24
const mvEMLINK = 31
const mvEMSGSIZE = 40
const mvEMULTIHOP = 95
const mvENABLE_BMAP_STATS = 1
const mvENAMETOOLONG = 63
const mvENEEDAUTH = 81
const mvENETDOWN = 50
const mvENETRESET = 52
const mvENETUNREACH = 51
const mvENFILE = 23
const mvENOATTR = 93
const mvENOBUFS = 55
const mvENODATA = 96
const mvENODEV = 19
const mvENOENT = 2
const mvENOEXEC = 8
const mvENOLCK = 77
const mvENOLINK = 97
const mvENOMEM = 12
const mvENOMSG = 91
const mvENOPOLICY = 103
const mvENOPROTOOPT = 42
const mvENOSPC = 28
const mvENOSR = 98
const mvENOSTR = 99
const mvENOSYS = 78
const mvENOTBLK = 15
const mvENOTCAPABLE = 107
const mvENOTCONN = 57
const mvENOTDIR = 20
const mvENOTEMPTY = 66
const mvENOTRECOVERABLE = 104
const mvENOTSOCK = 38
const mvENOTSUP = 45
const mvENOTTY = 25
const mvENXIO = 6
const mvEOPNOTSUPP = 102
const mvEOVERFLOW = 84
const mvEOWNERDEAD = 105
const mvEPERM = 1
const mvEPFNOSUPPORT = 46
const mvEPIPE = 32
const mvEPROCLIM = 67
const mvEPROCUNAVAIL = 76
const mvEPROGMISMATCH = 75
const mvEPROGUNAVAIL = 74
const mvEPROTO = 100
const mvEPROTONOSUPPORT = 43
const mvEPROTOTYPE = 41
const mvEPWROFF = 82
const mvEQFULL = 106
const mvERANGE = 34
const mvEREMOTE = 71
const mvEROFS = 30
const mvERPCMISMATCH = 73
const mvERRCODE_RANGE = 8
const mvESHLIBVERS = 87
const mvESHUTDOWN = 58
const mvESOCKTNOSUPPORT = 44
const mvESPIPE = 29
const mvESRCH = 3
const mvESTALE = 70
const mvETIME = 101
const mvETIMEDOUT = 60
const mvETOOMANYREFS = 59
const mvETXTBSY = 26
const mvEUSERS = 68
const mvEWOULDBLOCK = "EAGAIN"
const mvEXDEV = 18
const mvHAVE_BACKTRACE = 1
const mvHAVE_BSD_QSORT_R = 1
const mvHAVE_CFLOCALECOPYPREFERREDLANGUAGES = 1
const mvHAVE_CFPREFERENCESCOPYAPPVALUE = 1
const mvHAVE_CHFLAGS = 1
const mvHAVE_CONFIG_H = 1
const mvHAVE_DIRENT_H = 1
const mvHAVE_DLOPEN = 1
const mvHAVE_ERRNO_H = 1
const mvHAVE_EXECINFO_H = 1
const mvHAVE_FCHOWN = 1
const mvHAVE_FCNTL = 1
const mvHAVE_FDATASYNC = 1
const mvHAVE_FSTAT64 = 1
const mvHAVE_FSYNC = 1
const mvHAVE_FUTIMES = 1
const mvHAVE_GETCWD = 1
const mvHAVE_GETDTABLESIZE = 1
const mvHAVE_GETENTROPY = 1
const mvHAVE_GETHOSTNAME = 1
const mvHAVE_GETMNTINFO = 1
const mvHAVE_GETOPT_H = 1
const mvHAVE_GETPWUID_R = 1
const mvHAVE_GETRLIMIT = 1
const mvHAVE_GETRUSAGE = 1
const mvHAVE_INTPTR_T = 1
const mvHAVE_INTTYPES_H = 1
const mvHAVE_JRAND48 = 1
const mvHAVE_MBSTOWCS = 1
const mvHAVE_MMAP = 1
const mvHAVE_MOUNT_NODEV = 1
const mvHAVE_MOUNT_NOSUID = 1
const mvHAVE_MSYNC = 1
const mvHAVE_NANOSLEEP = 1
const mvHAVE_NETINET_IN_H = 1
const mvHAVE_NET_IF_DL_H = 1
const mvHAVE_NET_IF_H = 1
const mvHAVE_OPTRESET = 1
const mvHAVE_PATHCONF = 1
const mvHAVE_PATHS_H = 1
const mvHAVE_POSIX_MEMALIGN = 1
const mvHAVE_PREAD = 1
const mvHAVE_PTHREAD = 1
const mvHAVE_PTHREAD_H = 1
const mvHAVE_PTHREAD_PRIO_INHERIT = 1
const mvHAVE_PWRITE = 1
const mvHAVE_QSORT_R = 1
const mvHAVE_RECLEN_DIRENT = 1
const mvHAVE_SA_LEN = 1
const mvHAVE_SEMAPHORE_H = 1
const mvHAVE_SETJMP_H = 1
const mvHAVE_SIGNAL_H = 1
const mvHAVE_SNPRINTF = 1
const mvHAVE_SRANDOM = 1
const mvHAVE_STAT_FLAGS = 1
const mvHAVE_STDARG_H = 1
const mvHAVE_STDINT_H = 1
const mvHAVE_STDIO_H = 1
const mvHAVE_STDLIB_H = 1
const mvHAVE_STPCPY = 1
const mvHAVE_STRCASECMP = 1
const mvHAVE_STRDUP = 1
const mvHAVE_STRINGS_H = 1
const mvHAVE_STRING_H = 1
const mvHAVE_STRNLEN = 1
const mvHAVE_STRPTIME = 1
const mvHAVE_STRTOULL = 1
const mvHAVE_SYSCONF = 1
const mvHAVE_SYS_ACL_H = 1
const mvHAVE_SYS_DISK_H = 1
const mvHAVE_SYS_FILE_H = 1
const mvHAVE_SYS_IOCTL_H = 1
const mvHAVE_SYS_MMAN_H = 1
const mvHAVE_SYS_MOUNT_H = 1
const mvHAVE_SYS_RANDOM_H = 1
const mvHAVE_SYS_RESOURCE_H = 1
const mvHAVE_SYS_SELECT_H = 1
const mvHAVE_SYS_SOCKET_H = 1
const mvHAVE_SYS_SOCKIO_H = 1
const mvHAVE_SYS_STAT_H = 1
const mvHAVE_SYS_SYSCALL_H = 1
const mvHAVE_SYS_TIME_H = 1
const mvHAVE_SYS_TYPES_H = 1
const mvHAVE_SYS_UN_H = 1
const mvHAVE_SYS_WAIT_H = 1
const mvHAVE_SYS_XATTR_H = 1
const mvHAVE_TERMIOS_H = 1
const mvHAVE_TYPE_SSIZE_T = 1
const mvHAVE_UNISTD_H = 1
const mvHAVE_USLEEP = 1
const mvHAVE_UTIME = 1
const mvHAVE_UTIMES = 1
const mvHAVE_UTIME_H = 1
const mvHAVE_VALLOC = 1
const mvHAVE_VPRINTF = 1
const mvHAVE_WCHAR_H = 1
const mvLOCALEDIR = "/usr/local/share/locale"
const mvPACKAGE = "e2fsprogs"
const mvPACKAGE_BUGREPORT = ""
const mvPACKAGE_NAME = ""
const mvPACKAGE_STRING = ""
const mvPACKAGE_TARNAME = ""
const mvPACKAGE_URL = ""
const mvPACKAGE_VERSION = ""
const mvROOT_SYSCONFDIR = "/usr/local/etc"
const mvSIZEOF_INT = 4
const mvSIZEOF_LONG = 8
const mvSIZEOF_LONG_LONG = 8
const mvSIZEOF_OFF_T = 8
const mvSIZEOF_SHORT = 2
const mvSIZEOF_TIME_T = 8
const mvSIZEOF_VOID_P = 8
const mvSTDC_HEADERS = 1
const mvTARGET_IPHONE_SIMULATOR = 0
const mvTARGET_OS_ARROW = 1
const mvTARGET_OS_BRIDGE = 0
const mvTARGET_OS_DRIVERKIT = 0
const mvTARGET_OS_EMBEDDED = 0
const mvTARGET_OS_IOS = 0
const mvTARGET_OS_IOSMAC = 0
const mvTARGET_OS_IPHONE = 0
const mvTARGET_OS_LINUX = 0
const mvTARGET_OS_MAC = 1
const mvTARGET_OS_MACCATALYST = 0
const mvTARGET_OS_NANO = 0
const mvTARGET_OS_OSX = 1
const mvTARGET_OS_SIMULATOR = 0
const mvTARGET_OS_TV = 0
const mvTARGET_OS_UIKITFORMAC = 0
const mvTARGET_OS_UNIX = 0
const mvTARGET_OS_VISION = 0
const mvTARGET_OS_WATCH = 0
const mvTARGET_OS_WIN32 = 0
const mvTARGET_OS_WINDOWS = 0
const mvTARGET_OS_XR = 0
const mvVERSION = "0.14.1"
const mv_ALL_SOURCE = 1
const mv_DARWIN_C_SOURCE = 1
const mv_DARWIN_FEATURE_64_BIT_INODE = 1
const mv_DARWIN_FEATURE_ONLY_64_BIT_INODE = 1
const mv_DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1
const mv_DARWIN_FEATURE_ONLY_VERS_1050 = 1
const mv_DARWIN_FEATURE_UNIX_CONFORMANCE = 3
const mv_GNU_SOURCE = 1
const mv_HAS_BUILTIN_AVAILABLE_FEATS = 1
const mv_HPUX_ALT_XOPEN_SOCKET_API = 1
const mv_INTL_REDIRECT_MACROS = 1
const mv_LP64 = 1
const mv_NETBSD_SOURCE = 1
const mv_OPENBSD_SOURCE = 1
const mv_POSIX_PTHREAD_SEMANTICS = 1
const mv_TANDEM_SOURCE = 1
const mv__AARCH64EL__ = 1
const mv__AARCH64_CMODEL_SMALL__ = 1
const mv__AARCH64_SIMD__ = 1
const mv__APPLE_CC__ = 6000
const mv__APPLE__ = 1
const mv__ARM64_ARCH_8__ = 1
const mv__ARM_64BIT_STATE = 1
const mv__ARM_ACLE = 200
const mv__ARM_ALIGN_MAX_STACK_PWR = 4
const mv__ARM_ARCH = 8
const mv__ARM_ARCH_8_3__ = 1
const mv__ARM_ARCH_8_4__ = 1
const mv__ARM_ARCH_8_5__ = 1
const mv__ARM_ARCH_ISA_A64 = 1
const mv__ARM_ARCH_PROFILE = 'A'
const mv__ARM_FEATURE_AES = 1
const mv__ARM_FEATURE_ATOMICS = 1
const mv__ARM_FEATURE_BTI = 1
const mv__ARM_FEATURE_CLZ = 1
const mv__ARM_FEATURE_COMPLEX = 1
const mv__ARM_FEATURE_CRC32 = 1
const mv__ARM_FEATURE_CRYPTO = 1
const mv__ARM_FEATURE_DIRECTED_ROUNDING = 1
const mv__ARM_FEATURE_DIV = 1
const mv__ARM_FEATURE_DOTPROD = 1
const mv__ARM_FEATURE_FMA = 1
const mv__ARM_FEATURE_FP16_FML = 1
const mv__ARM_FEATURE_FP16_SCALAR_ARITHMETIC = 1
const mv__ARM_FEATURE_FP16_VECTOR_ARITHMETIC = 1
const mv__ARM_FEATURE_FRINT = 1
const mv__ARM_FEATURE_IDIV = 1
const mv__ARM_FEATURE_JCVT = 1
const mv__ARM_FEATURE_LDREX = 0xF
const mv__ARM_FEATURE_NUMERIC_MAXMIN = 1
const mv__ARM_FEATURE_PAUTH = 1
const mv__ARM_FEATURE_QRDMX = 1
const mv__ARM_FEATURE_RCPC = 1
const mv__ARM_FEATURE_SHA2 = 1
const mv__ARM_FEATURE_SHA3 = 1
const mv__ARM_FEATURE_SHA512 = 1
const mv__ARM_FEATURE_UNALIGNED = 1
const mv__ARM_FP = 0xE
const mv__ARM_FP16_ARGS = 1
const mv__ARM_FP16_FORMAT_IEEE = 1
const mv__ARM_NEON = 1
const mv__ARM_NEON_FP = 0xE
const mv__ARM_NEON__ = 1
const mv__ARM_PCS_AAPCS64 = 1
const mv__ARM_SIZEOF_MINIMAL_ENUM = 4
const mv__ARM_SIZEOF_WCHAR_T = 4
const mv__ARM_STATE_ZA = 1
const mv__ARM_STATE_ZT0 = 1
const mv__ATOMIC_ACQUIRE = 2
const mv__ATOMIC_ACQ_REL = 4
const mv__ATOMIC_CONSUME = 1
const mv__ATOMIC_RELAXED = 0
const mv__ATOMIC_RELEASE = 3
const mv__ATOMIC_SEQ_CST = 5
const mv__BIGGEST_ALIGNMENT__ = 8
const mv__BITINT_MAXWIDTH__ = 128
const mv__BLOCKS__ = 1
const mv__BOOL_WIDTH__ = 8
const mv__BYTE_ORDER__ = "__ORDER_LITTLE_ENDIAN__"
const mv__CCGO__ = 1
const mv__CHAR_BIT__ = 8
const mv__CLANG_ATOMIC_BOOL_LOCK_FREE = 2
const mv__CLANG_ATOMIC_CHAR16_T_LOCK_FREE = 2
const mv__CLANG_ATOMIC_CHAR32_T_LOCK_FREE = 2
const mv__CLANG_ATOMIC_CHAR_LOCK_FREE = 2
const mv__CLANG_ATOMIC_INT_LOCK_FREE = 2
const mv__CLANG_ATOMIC_LLONG_LOCK_FREE = 2
const mv__CLANG_ATOMIC_LONG_LOCK_FREE = 2
const mv__CLANG_ATOMIC_POINTER_LOCK_FREE = 2
const mv__CLANG_ATOMIC_SHORT_LOCK_FREE = 2
const mv__CLANG_ATOMIC_WCHAR_T_LOCK_FREE = 2
const mv__CONSTANT_CFSTRINGS__ = 1
const mv__DARWIN_64_BIT_INO_T = 1
const mv__DARWIN_C_ANSI = 010000
const mv__DARWIN_C_FULL = 900000
const mv__DARWIN_C_LEVEL = "__DARWIN_C_FULL"
const mv__DARWIN_NON_CANCELABLE = 0
const mv__DARWIN_NO_LONG_LONG = 0
const mv__DARWIN_ONLY_64_BIT_INO_T = 1
const mv__DARWIN_ONLY_UNIX_CONFORMANCE = 1
const mv__DARWIN_ONLY_VERS_1050 = 1
const mv__DARWIN_SUF_EXTSN = "$DARWIN_EXTSN"
const mv__DARWIN_UNIX03 = 1
const mv__DARWIN_VERS_1050 = 1
const mv__DBL_DECIMAL_DIG__ = 17
const mv__DBL_DENORM_MIN__ = 4.9406564584124654e-324
const mv__DBL_DIG__ = 15
const mv__DBL_EPSILON__ = 2.2204460492503131e-16
const mv__DBL_HAS_DENORM__ = 1
const mv__DBL_HAS_INFINITY__ = 1
const mv__DBL_HAS_QUIET_NAN__ = 1
const mv__DBL_MANT_DIG__ = 53
const mv__DBL_MAX_10_EXP__ = 308
const mv__DBL_MAX_EXP__ = 1024
const mv__DBL_MAX__ = 1.7976931348623157e+308
const mv__DBL_MIN__ = 2.2250738585072014e-308
const mv__DBL_NORM_MAX__ = 1.7976931348623157e+308
const mv__DECIMAL_DIG__ = "__LDBL_DECIMAL_DIG__"
const mv__DYNAMIC__ = 1
const mv__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ = 260000
const mv__ENVIRONMENT_OS_VERSION_MIN_REQUIRED__ = 260000
const mv__EXTENSIONS__ = 1
const mv__FINITE_MATH_ONLY__ = 0
const mv__FLT16_DECIMAL_DIG__ = 5
const mv__FLT16_DENORM_MIN__ = 5.9604644775390625e-8
const mv__FLT16_DIG__ = 3
const mv__FLT16_EPSILON__ = 9.765625e-4
const mv__FLT16_HAS_DENORM__ = 1
const mv__FLT16_HAS_INFINITY__ = 1
const mv__FLT16_HAS_QUIET_NAN__ = 1
const mv__FLT16_MANT_DIG__ = 11
const mv__FLT16_MAX_10_EXP__ = 4
const mv__FLT16_MAX_EXP__ = 16
const mv__FLT16_MAX__ = 6.5504e+4
const mv__FLT16_MIN__ = 6.103515625e-5
const mv__FLT16_NORM_MAX__ = 6.5504e+4
const mv__FLT_DECIMAL_DIG__ = 9
const mv__FLT_DENORM_MIN__ = 1.40129846e-45
const mv__FLT_DIG__ = 6
const mv__FLT_EPSILON__ = 1.19209290e-7
const mv__FLT_HAS_DENORM__ = 1
const mv__FLT_HAS_INFINITY__ = 1
const mv__FLT_HAS_QUIET_NAN__ = 1
const mv__FLT_MANT_DIG__ = 24
const mv__FLT_MAX_10_EXP__ = 38
const mv__FLT_MAX_EXP__ = 128
const mv__FLT_MAX__ = 3.40282347e+38
const mv__FLT_MIN__ = 1.17549435e-38
const mv__FLT_NORM_MAX__ = 3.40282347e+38
const mv__FLT_RADIX__ = 2
const mv__FPCLASS_NEGINF = 0x0004
const mv__FPCLASS_NEGNORMAL = 0x0008
const mv__FPCLASS_NEGSUBNORMAL = 0x0010
const mv__FPCLASS_NEGZERO = 0x0020
const mv__FPCLASS_POSINF = 0x0200
const mv__FPCLASS_POSNORMAL = 0x0100
const mv__FPCLASS_POSSUBNORMAL = 0x0080
const mv__FPCLASS_POSZERO = 0x0040
const mv__FPCLASS_QNAN = 0x0002
const mv__FPCLASS_SNAN = 0x0001
const mv__FP_FAST_FMA = 1
const mv__FP_FAST_FMAF = 1
const mv__FUNCTION__ = "__func__"
const mv__GCC_ASM_FLAG_OUTPUTS__ = 1
const mv__GCC_ATOMIC_BOOL_LOCK_FREE = 2
const mv__GCC_ATOMIC_CHAR16_T_LOCK_FREE = 2
const mv__GCC_ATOMIC_CHAR32_T_LOCK_FREE = 2
const mv__GCC_ATOMIC_CHAR_LOCK_FREE = 2
const mv__GCC_ATOMIC_INT_LOCK_FREE = 2
const mv__GCC_ATOMIC_LLONG_LOCK_FREE = 2
const mv__GCC_ATOMIC_LONG_LOCK_FREE = 2
const mv__GCC_ATOMIC_POINTER_LOCK_FREE = 2
const mv__GCC_ATOMIC_SHORT_LOCK_FREE = 2
const mv__GCC_ATOMIC_TEST_AND_SET_TRUEVAL = 1
const mv__GCC_ATOMIC_WCHAR_T_LOCK_FREE = 2
const mv__GCC_CONSTRUCTIVE_SIZE = 64
const mv__GCC_DESTRUCTIVE_SIZE = 64
const mv__GCC_HAVE_DWARF2_CFI_ASM = 1
const mv__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 = 1
const mv__GCC_HAVE_SYNC_COMPARE_AND_SWAP_16 = 1
const mv__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 = 1
const mv__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 = 1
const mv__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 = 1
const mv__GNUC_MINOR__ = 2
const mv__GNUC_PATCHLEVEL__ = 1
const mv__GNUC_STDC_INLINE__ = 1
const mv__GNUC__ = 4
const mv__GXX_ABI_VERSION = 1002
const mv__HAVE_FUNCTION_MULTI_VERSIONING = 1
const mv__INT16_FMTd__ = "hd"
const mv__INT16_FMTi__ = "hi"
const mv__INT16_MAX__ = 32767
const mv__INT16_TYPE__ = "short"
const mv__INT32_FMTd__ = "d"
const mv__INT32_FMTi__ = "i"
const mv__INT32_MAX__ = 2147483647
const mv__INT32_TYPE__ = "int"
const mv__INT64_C_SUFFIX__ = "LL"
const mv__INT64_FMTd__ = "lld"
const mv__INT64_FMTi__ = "lli"
const mv__INT64_MAX__ = 9223372036854775807
const mv__INT8_FMTd__ = "hhd"
const mv__INT8_FMTi__ = "hhi"
const mv__INT8_MAX__ = 127
const mv__INTMAX_C_SUFFIX__ = "L"
const mv__INTMAX_FMTd__ = "ld"
const mv__INTMAX_FMTi__ = "li"
const mv__INTMAX_MAX__ = 9223372036854775807
const mv__INTMAX_WIDTH__ = 64
const mv__INTPTR_FMTd__ = "ld"
const mv__INTPTR_FMTi__ = "li"
const mv__INTPTR_MAX__ = 9223372036854775807
const mv__INTPTR_WIDTH__ = 64
const mv__INT_FAST16_FMTd__ = "hd"
const mv__INT_FAST16_FMTi__ = "hi"
const mv__INT_FAST16_MAX__ = 32767
const mv__INT_FAST16_TYPE__ = "short"
const mv__INT_FAST16_WIDTH__ = 16
const mv__INT_FAST32_FMTd__ = "d"
const mv__INT_FAST32_FMTi__ = "i"
const mv__INT_FAST32_MAX__ = 2147483647
const mv__INT_FAST32_TYPE__ = "int"
const mv__INT_FAST32_WIDTH__ = 32
const mv__INT_FAST64_FMTd__ = "lld"
const mv__INT_FAST64_FMTi__ = "lli"
const mv__INT_FAST64_MAX__ = 9223372036854775807
const mv__INT_FAST64_WIDTH__ = 64
const mv__INT_FAST8_FMTd__ = "hhd"
const mv__INT_FAST8_FMTi__ = "hhi"
const mv__INT_FAST8_MAX__ = 127
const mv__INT_FAST8_WIDTH__ = 8
const mv__INT_LEAST16_FMTd__ = "hd"
const mv__INT_LEAST16_FMTi__ = "hi"
const mv__INT_LEAST16_MAX__ = 32767
const mv__INT_LEAST16_TYPE__ = "short"
const mv__INT_LEAST16_WIDTH__ = 16
const mv__INT_LEAST32_FMTd__ = "d"
const mv__INT_LEAST32_FMTi__ = "i"
const mv__INT_LEAST32_MAX__ = 2147483647
const mv__INT_LEAST32_TYPE__ = "int"
const mv__INT_LEAST32_WIDTH__ = 32
const mv__INT_LEAST64_FMTd__ = "lld"
const mv__INT_LEAST64_FMTi__ = "lli"
const mv__INT_LEAST64_MAX__ = 9223372036854775807
const mv__INT_LEAST64_WIDTH__ = 64
const mv__INT_LEAST8_FMTd__ = "hhd"
const mv__INT_LEAST8_FMTi__ = "hhi"
const mv__INT_LEAST8_MAX__ = 127
const mv__INT_LEAST8_WIDTH__ = 8
const mv__INT_MAX__ = 2147483647
const mv__INT_WIDTH__ = 32
const mv__LDBL_DECIMAL_DIG__ = 17
const mv__LDBL_DENORM_MIN__ = 4.9406564584124654e-324
const mv__LDBL_DIG__ = 15
const mv__LDBL_EPSILON__ = 2.2204460492503131e-16
const mv__LDBL_HAS_DENORM__ = 1
const mv__LDBL_HAS_INFINITY__ = 1
const mv__LDBL_HAS_QUIET_NAN__ = 1
const mv__LDBL_MANT_DIG__ = 53
const mv__LDBL_MAX_10_EXP__ = 308
const mv__LDBL_MAX_EXP__ = 1024
const mv__LDBL_MAX__ = 1.7976931348623157e+308
const mv__LDBL_MIN__ = 2.2250738585072014e-308
const mv__LDBL_NORM_MAX__ = 1.7976931348623157e+308
const mv__LITTLE_ENDIAN__ = 1
const mv__LLONG_WIDTH__ = 64
const mv__LONG_LONG_MAX__ = 9223372036854775807
const mv__LONG_MAX__ = 9223372036854775807
const mv__LONG_WIDTH__ = 64
const mv__LP64__ = 1
const mv__MACH__ = 1
const mv__MEMORY_SCOPE_DEVICE = 1
const mv__MEMORY_SCOPE_SINGLE = 4
const mv__MEMORY_SCOPE_SYSTEM = 0
const mv__MEMORY_SCOPE_WRKGRP = 2
const mv__MEMORY_SCOPE_WVFRNT = 3
const mv__NO_INLINE__ = 1
const mv__NO_MATH_ERRNO__ = 1
const mv__OBJC_BOOL_IS_BOOL = 1
const mv__OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES = 3
const mv__OPENCL_MEMORY_SCOPE_DEVICE = 2
const mv__OPENCL_MEMORY_SCOPE_SUB_GROUP = 4
const mv__OPENCL_MEMORY_SCOPE_WORK_GROUP = 1
const mv__OPENCL_MEMORY_SCOPE_WORK_ITEM = 0
const mv__ORDER_BIG_ENDIAN__ = 4321
const mv__ORDER_LITTLE_ENDIAN__ = 1234
const mv__ORDER_PDP_ENDIAN__ = 3412
const mv__PIC__ = 2
const mv__POINTER_WIDTH__ = 64
const mv__PRAGMA_REDEFINE_EXTNAME = 1
const mv__PRETTY_FUNCTION__ = "__func__"
const mv__PTRDIFF_FMTd__ = "ld"
const mv__PTRDIFF_FMTi__ = "li"
const mv__PTRDIFF_MAX__ = 9223372036854775807
const mv__PTRDIFF_WIDTH__ = 64
const mv__SCHAR_MAX__ = 127
const mv__SHRT_MAX__ = 32767
const mv__SHRT_WIDTH__ = 16
const mv__SIG_ATOMIC_MAX__ = 2147483647
const mv__SIG_ATOMIC_WIDTH__ = 32
const mv__SIZEOF_DOUBLE__ = 8
const mv__SIZEOF_FLOAT__ = 4
const mv__SIZEOF_INT128__ = 16
const mv__SIZEOF_INT__ = 4
const mv__SIZEOF_LONG_DOUBLE__ = 8
const mv__SIZEOF_LONG_LONG__ = 8
const mv__SIZEOF_LONG__ = 8
const mv__SIZEOF_POINTER__ = 8
const mv__SIZEOF_PTRDIFF_T__ = 8
const mv__SIZEOF_SHORT__ = 2
const mv__SIZEOF_SIZE_T__ = 8
const mv__SIZEOF_WCHAR_T__ = 4
const mv__SIZEOF_WINT_T__ = 4
const mv__SIZE_FMTX__ = "lX"
const mv__SIZE_FMTo__ = "lo"
const mv__SIZE_FMTu__ = "lu"
const mv__SIZE_FMTx__ = "lx"
const mv__SIZE_MAX__ = 18446744073709551615
const mv__SIZE_WIDTH__ = 64
const mv__SSP__ = 1
const mv__STDC_EMBED_EMPTY__ = 2
const mv__STDC_EMBED_FOUND__ = 1
const mv__STDC_EMBED_NOT_FOUND__ = 0
const mv__STDC_HOSTED__ = 1
const mv__STDC_NO_THREADS__ = 1
const mv__STDC_UTF_16__ = 1
const mv__STDC_UTF_32__ = 1
const mv__STDC_VERSION__ = 201710
const mv__STDC_WANT_IEC_60559_ATTRIBS_EXT__ = 1
const mv__STDC_WANT_IEC_60559_BFP_EXT__ = 1
const mv__STDC_WANT_IEC_60559_DFP_EXT__ = 1
const mv__STDC_WANT_IEC_60559_EXT__ = 1
const mv__STDC_WANT_IEC_60559_FUNCS_EXT__ = 1
const mv__STDC_WANT_IEC_60559_TYPES_EXT__ = 1
const mv__STDC_WANT_LIB_EXT1__ = 1
const mv__STDC_WANT_LIB_EXT2__ = 1
const mv__STDC_WANT_MATH_SPEC_FUNCS__ = 1
const mv__STDC__ = 1
const mv__UINT16_FMTX__ = "hX"
const mv__UINT16_FMTo__ = "ho"
const mv__UINT16_FMTu__ = "hu"
const mv__UINT16_FMTx__ = "hx"
const mv__UINT16_MAX__ = 65535
const mv__UINT32_C_SUFFIX__ = "U"
const mv__UINT32_FMTX__ = "X"
const mv__UINT32_FMTo__ = "o"
const mv__UINT32_FMTu__ = "u"
const mv__UINT32_FMTx__ = "x"
const mv__UINT32_MAX__ = 4294967295
const mv__UINT64_C_SUFFIX__ = "ULL"
const mv__UINT64_FMTX__ = "llX"
const mv__UINT64_FMTo__ = "llo"
const mv__UINT64_FMTu__ = "llu"
const mv__UINT64_FMTx__ = "llx"
const mv__UINT64_MAX__ = "18446744073709551615U"
const mv__UINT8_FMTX__ = "hhX"
const mv__UINT8_FMTo__ = "hho"
const mv__UINT8_FMTu__ = "hhu"
const mv__UINT8_FMTx__ = "hhx"
const mv__UINT8_MAX__ = 255
const mv__UINTMAX_C_SUFFIX__ = "UL"
const mv__UINTMAX_FMTX__ = "lX"
const mv__UINTMAX_FMTo__ = "lo"
const mv__UINTMAX_FMTu__ = "lu"
const mv__UINTMAX_FMTx__ = "lx"
const mv__UINTMAX_MAX__ = 18446744073709551615
const mv__UINTMAX_WIDTH__ = 64
const mv__UINTPTR_FMTX__ = "lX"
const mv__UINTPTR_FMTo__ = "lo"
const mv__UINTPTR_FMTu__ = "lu"
const mv__UINTPTR_FMTx__ = "lx"
const mv__UINTPTR_MAX__ = 18446744073709551615
const mv__UINTPTR_WIDTH__ = 64
const mv__UINT_FAST16_FMTX__ = "hX"
const mv__UINT_FAST16_FMTo__ = "ho"
const mv__UINT_FAST16_FMTu__ = "hu"
const mv__UINT_FAST16_FMTx__ = "hx"
const mv__UINT_FAST16_MAX__ = 65535
const mv__UINT_FAST32_FMTX__ = "X"
const mv__UINT_FAST32_FMTo__ = "o"
const mv__UINT_FAST32_FMTu__ = "u"
const mv__UINT_FAST32_FMTx__ = "x"
const mv__UINT_FAST32_MAX__ = 4294967295
const mv__UINT_FAST64_FMTX__ = "llX"
const mv__UINT_FAST64_FMTo__ = "llo"
const mv__UINT_FAST64_FMTu__ = "llu"
const mv__UINT_FAST64_FMTx__ = "llx"
const mv__UINT_FAST64_MAX__ = "18446744073709551615U"
const mv__UINT_FAST8_FMTX__ = "hhX"
const mv__UINT_FAST8_FMTo__ = "hho"
const mv__UINT_FAST8_FMTu__ = "hhu"
const mv__UINT_FAST8_FMTx__ = "hhx"
const mv__UINT_FAST8_MAX__ = 255
const mv__UINT_LEAST16_FMTX__ = "hX"
const mv__UINT_LEAST16_FMTo__ = "ho"
const mv__UINT_LEAST16_FMTu__ = "hu"
const mv__UINT_LEAST16_FMTx__ = "hx"
const mv__UINT_LEAST16_MAX__ = 65535
const mv__UINT_LEAST32_FMTX__ = "X"
const mv__UINT_LEAST32_FMTo__ = "o"
const mv__UINT_LEAST32_FMTu__ = "u"
const mv__UINT_LEAST32_FMTx__ = "x"
const mv__UINT_LEAST32_MAX__ = 4294967295
const mv__UINT_LEAST64_FMTX__ = "llX"
const mv__UINT_LEAST64_FMTo__ = "llo"
const mv__UINT_LEAST64_FMTu__ = "llu"
const mv__UINT_LEAST64_FMTx__ = "llx"
const mv__UINT_LEAST64_MAX__ = "18446744073709551615U"
const mv__UINT_LEAST8_FMTX__ = "hhX"
const mv__UINT_LEAST8_FMTo__ = "hho"
const mv__UINT_LEAST8_FMTu__ = "hhu"
const mv__UINT_LEAST8_FMTx__ = "hhx"
const mv__UINT_LEAST8_MAX__ = 255
const mv__USER_LABEL_PREFIX__ = "_"
const mv__VERSION__ = "Apple LLVM 17.0.0 (clang-1700.3.19.1)"
const mv__WCHAR_MAX__ = 2147483647
const mv__WCHAR_TYPE__ = "int"
const mv__WCHAR_WIDTH__ = 32
const mv__WINT_MAX__ = 2147483647
const mv__WINT_TYPE__ = "int"
const mv__WINT_WIDTH__ = 32
const mv__aarch64__ = 1
const mv__apple_build_version__ = 17000319
const mv__arm64 = 1
const mv__arm64__ = 1
const mv__clang__ = 1
const mv__clang_literal_encoding__ = "UTF-8"
const mv__clang_major__ = 17
const mv__clang_minor__ = 0
const mv__clang_patchlevel__ = 0
const mv__clang_version__ = "17.0.0 (clang-1700.3.19.1)"
const mv__clang_wide_literal_encoding__ = "UTF-32"
const mv__const = "const"
const mv__exported_hidden = "__private_extern__"
const mv__has_bounds_safety_attributes = 0
const mv__has_ptrcheck = 0
const mv__has_safe_buffers = 0
const mv__header_inline = "inline"
const mv__llvm__ = 1
const mv__nonnull = "_Nonnull"
const mv__null_unspecified = "_Null_unspecified"
const mv__nullable = "_Nullable"
const mv__pic__ = 2
const mv__restrict = "restrict"
const mv__restrict_arr = "restrict"
const mv__signed = "signed"
const mv__volatile = "volatile"

type tn__builtin_va_list = ppuintptr

type tn__predefined_size_t = ppuint64

type tn__predefined_wchar_t = ppint32

type tn__predefined_ptrdiff_t = ppint64

type tnptrdiff_t = ppint64

type tnsize_t = ppuint64

type tnwchar_t = ppint32

type tnmax_align_t = ppfloat64

type tn__gnuc_va_list = ppuintptr

type tnva_list = ppuintptr

type tnerrcode_t = ppint64

type tserror_table = struct {
	fdmsgs   ppuintptr
	fdbase   ppint64
	fdn_msgs ppint32
}

type tset_list = struct {
	fdnext  ppuintptr
	fdtable ppuintptr
}

type tnerrno_t = ppint32

/*
 * Error codes
 */

/* 11 was EAGAIN */

/* math software */

/* non-blocking and interrupt i/o */

/* ipc/network software -- argument errors */

/* ipc/network software -- operational errors */

/* should be rearranged */

/* quotas & mush */

/* Network File System */

/* Intelligent device errors */

/* Program loading errors */

/* This value is only discrete when compiling __DARWIN_UNIX03, or KERNEL */

var sichar_set = [64]ppint8{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '_'}

var sibuf [6]ppint8

func Xerror_table_name(cgtls *iqlibc.ppTLS, aanum tnerrcode_t) (cgr ppuintptr) {

	var aach, aai ppint32
	var aap, ccv2 ppuintptr
	pp_, pp_, pp_, pp_ = aach, aai, aap, ccv2

	/* num = aa aaa abb bbb bcc ccc cdd ddd d?? ??? ??? */
	aap = ppuintptr(iqunsafe.ppPointer(&sibuf))
	aanum = aanum >> ppint64(mvERRCODE_RANGE)
	/* num = ?? ??? ??? aaa aaa bbb bbb ccc ccc ddd ddd */
	aanum = aanum & ppint64(077777777)
	/* num = 00 000 000 aaa aaa bbb bbb ccc ccc ddd ddd */
	aai = ppint32(4)
	for {
		if !(aai >= 0) {
			break
		}
		aach = ppint32(aanum >> (iqlibc.ppInt32FromInt32(mvBITS_PER_CHAR) * aai) & ppint64(iqlibc.ppInt32FromInt32(1)<<iqlibc.ppInt32FromInt32(mvBITS_PER_CHAR)-iqlibc.ppInt32FromInt32(1)))
		if aach != 0 {
			ccv2 = aap
			aap = aap + 1
			*(*ppint8)(iqunsafe.ppPointer(ccv2)) = sichar_set[aach-ppint32(1)]
		}

		goto cg_1
	cg_1:
		;
		aai = aai - 1
	}
	*(*ppint8)(iqunsafe.ppPointer(aap)) = ppint8('\000')
	return ppuintptr(iqunsafe.ppPointer(&sibuf))
}

const ___ccgo_meta_json = `{
	"Aliases": {},
	"Visibility": {},
	"WeakAliases": {}
}`
